version: "3.9"

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  # next-app:
  #   build:
  #     context: .
  #   depends_on:
  #     - database
  #   environment:
  #     DATABASE_URL: postgres://username:password@database:5432/mydb
