version: "3.8"

services:
    redis:
        image: redis:latest
        container_name: fsl-redis
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis:/data
        restart: always
