version: "3.8"

services:
    redis:
        image: redis:latest
        container_name: fsl-redis
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis:/data
        restart: always
    mongodb:
        image: mongo:latest
        container_name: fsl-mongodb
        ports:
            - "27017:27017"
        volumes:
            - ./data/mongodb:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        restart: always
