
@id=68024d0842139de9b6deccac
@token=hax

GET http://localhost:4000/api/test

###
POST http://localhost:4000/api/next
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{id}}"
}

###
# Bump when server restarts
POST http://localhost:4000/api/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{id}}"
}

{
  "id": "{{id}}"
}
###
GET http://localhost:4000/api/log/controller
###
POST http://localhost:4000/api/round
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{id}}"
}

###
POST http://localhost:4000/api/set-winner
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{id}}",
  "winner": "A"
}

###
POST http://localhost:4000/api/card
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "owner": "5f9d1b3b7f1f3b0017f3b3b1",
  "name": "X vs DDY",
  "fights": [
    {
      "totalRounds": 3,
      "sport": "MMA",
      "fighterA": "Puncher",
      "fighterB": "Kicker"
    },
    {
      "totalRounds": 4,
      "sport": "Boxing",
      "fighterA": "Lefty",
      "fighterB": "Righty"
    }
  ]
}

###
POST http://localhost:4000/api/finish
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{id}}",
  "outcome": "Knockout",
  "winner": "B"
}


###

GET http://localhost:4000/api/live-fights

###


POST http://localhost:4000/api/end-card
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{id}}"
}