
@id=67efd353d769fc5984f66ee4

GET http://localhost:4000/api/test

###
POST http://localhost:4000/api/next
Content-Type: application/json

{
  "id": "{{id}}"
}

###
# Bump when server restarts
POST http://localhost:4000/api/update
Content-Type: application/json

{
  "id": "{{id}}"
}
###
GET http://localhost:4000/api/log/controller
###
POST http://localhost:4000/api/round
Content-Type: application/json

{
  "id": "{{id}}"
}
###
POST http://localhost:4000/api/card
Content-Type: application/json

{
  "owner": "5f9d1b3b7f1f3b0017f3b3b1",
  "name": "Fight of the YEAR!",
  "fights": [
    {
      "totalRounds": 30,
      "sport": "MMA",
      "fighterA": "Puncher",
      "fighterB": "Kicker"
    },
    {
      "totalRounds": 4,
      "sport": "Boxing",
      "fighterA": "Lefty",
      "fighterB": "Righty"
    }
  ]
}
###
POST http://localhost:4000/api/finish
Content-Type: application/json

{
  "id": "{{id}}",
  "outcome": "Knockout"
}


###

GET http://localhost:4000/api/live-fights

###


POST http://localhost:4000/api/end-card
Content-Type: application/json

{
  "id": "{{id}}"
}